// TurboModule bridge for the iOS audio module.
//
// The work is in NightAudioImpl.swift; this file exists only because a
// TurboModule must conform to the Objective-C protocol that codegen emits
// (NativeNightAudioSpec, in AppSpecs), and Swift cannot conform to a protocol
// carrying C++ types. So: thin ObjC++ shell, Swift underneath.
//
// "SleepcastApp-Swift.h" is generated by Xcode from the Swift sources; if the
// target is renamed, this import name changes with it.

#import <React/RCTBridgeModule.h>
#import <AppSpecs/AppSpecs.h>
#import "SleepcastApp-Swift.h"

@interface NightAudio : NSObject <NativeNightAudioSpec>
@end

@implementation NightAudio

RCT_EXPORT_MODULE()

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeNightAudioSpecJSI>(params);
}

- (void)play:(NSString *)url
    startAtSeconds:(double)startAtSeconds
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject
{
  [[NightAudioImpl shared] play:url
                        startAt:startAtSeconds
                        resolve:^(id result) { resolve(result); }
                         reject:^(NSString *code, NSString *message) {
                           reject(code, message, nil);
                         }];
}

- (void)pause { [[NightAudioImpl shared] pause]; }
- (void)resume { [[NightAudioImpl shared] resume]; }
- (void)stop { [[NightAudioImpl shared] stop]; }

- (void)setVolume:(double)volume { [[NightAudioImpl shared] setVolume:volume]; }

- (void)getPosition:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  resolve(@([[NightAudioImpl shared] getPosition]));
}

- (void)getDuration:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  resolve(@([[NightAudioImpl shared] getDuration]));
}

- (void)isPlaying:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  resolve(@([[NightAudioImpl shared] isPlaying]));
}

- (void)setNowPlaying:(NSString *)title
               artist:(NSString *)artist
           artworkUrl:(NSString *)artworkUrl
      durationSeconds:(double)durationSeconds
{
  [[NightAudioImpl shared] setNowPlaying:title
                                  artist:artist
                              artworkUrl:artworkUrl
                                duration:durationSeconds];
}

@end
