// TurboModule bridge for the iOS audio module.
//
// The work is in NightAudioImpl.swift; this file exists only because a
// TurboModule must conform to the Objective-C protocol that codegen emits
// (NativeNightAudioSpec, in AppSpecs), and Swift cannot conform to a protocol
// carrying C++ types. So: thin ObjC++ shell, Swift underneath.
//
// "SleepcastApp-Swift.h" is generated by Xcode from the Swift sources; if the
// target is renamed, this import name changes with it.

#import <React/RCTBridgeModule.h>
#import <AppSpecs/AppSpecs.h>
// SleepcastApp-Swift.h re-declares every @objc Swift class in the target,
// including AppDelegate's ReactNativeDelegate, whose superclass
// (RCTDefaultReactNativeFactoryDelegate) must be visible first or this file
// fails to compile with "cannot find interface declaration".
#import <React-RCTAppDelegate/RCTDefaultReactNativeFactoryDelegate.h>
#import "SleepcastApp-Swift.h"

// Subclassing NativeNightAudioSpecBase (not NSObject) is what wires the
// codegen event path: the base class holds the EventEmitterCallback that the
// TurboModule infra installs, and exposes emitOnNightEnded: to fire the
// onNightEnded event declared in the spec. Same design Android confirmed —
// no JS-side change needed.
@interface NightAudio : NativeNightAudioSpecBase <NativeNightAudioSpec>
@end

@implementation NightAudio

RCT_EXPORT_MODULE()

- (instancetype)init
{
  if (self = [super init]) {
    __weak NightAudio *weakSelf = self;
    [NightAudioImpl shared].onNightEnded = ^(NSString *episodeId, NSInteger heardSeconds) {
      [weakSelf emitOnNightEnded:@{
        @"episodeId" : episodeId,
        @"heardSeconds" : @(heardSeconds),
      }];
    };
  }
  return self;
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeNightAudioSpecJSI>(params);
}

- (void)play:(NSString *)url
    startAtSeconds:(double)startAtSeconds
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject
{
  [[NightAudioImpl shared] play:url
                        startAt:startAtSeconds
                        resolve:^(id result) { resolve(result); }
                         reject:^(NSString *code, NSString *message) {
                           reject(code, message, nil);
                         }];
}

- (void)pause { [[NightAudioImpl shared] pause]; }
- (void)resume { [[NightAudioImpl shared] resume]; }
- (void)stop { [[NightAudioImpl shared] stop]; }

- (void)setVolume:(double)volume { [[NightAudioImpl shared] setVolume:volume]; }

- (void)getPosition:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  resolve(@([[NightAudioImpl shared] getPosition]));
}

- (void)getDuration:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  resolve(@([[NightAudioImpl shared] getDuration]));
}

- (void)isPlaying:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  resolve(@([[NightAudioImpl shared] isPlaying]));
}

- (void)setNowPlaying:(NSString *)title
               artist:(NSString *)artist
           artworkUrl:(NSString *)artworkUrl
      durationSeconds:(double)durationSeconds
{
  [[NightAudioImpl shared] setNowPlaying:title
                                  artist:artist
                              artworkUrl:artworkUrl
                                duration:durationSeconds];
}

- (void)scheduleFadeAndStop:(NSString *)episodeId
            durationSeconds:(double)durationSeconds
                fadeSeconds:(double)fadeSeconds
{
  [[NightAudioImpl shared] scheduleFadeAndStop:episodeId
                               durationSeconds:durationSeconds
                                   fadeSeconds:fadeSeconds];
}

- (void)cancelTimer { [[NightAudioImpl shared] cancelTimer]; }

@end
